<a href="https://colab.research.google.com/github/thekhush11/GenAI-Colab-Projects/blob/main/Backpropagation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

25/07/2025

#Topics -
* Backpropogation and Optimization
* Overfitting and Regularization
* About the Pytorch

# Backpropogation -
It is the learning algorithm that allow our neural network to learn by adjusting weights based on the error(loss)

#Steps-
1. Forward Pass - Input data is fed through the network layer by layer, with each neuron calculating a weighted sum of its inputs and applying an activation function. This process culminates in a predicted output from the output layer.


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import BinaryCrossentropy

In [ ]:
#Use Iris Data -
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelBinarizer, StandardScaler

In [ ]:
iris = load_iris()
x = iris.data
y = iris.target
print(x, "\n")

print(y, "\n")

print(np.unique(x), "\n")
print(np.unique(y))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [ ]:
#Use LabelBinarizer
data = LabelBinarizer()
data1 = data.fit_transform(y)

#Normalizer Feature
scaler = StandardScaler()
Scaled = scaler.fit_transform(x)

print(Scaled)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(Scaled, data1, test_size=0.2, random_state = 42)

print(x_train.shape, "\n")

print(y_test.shape, "\n")

print(x_test.shape, "\n")

print(y_train.shape)

(120, 4) 

(30, 3) 

(30, 4) 

(120, 3)


In [ ]:
#Create Model -
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import SGD
from tensorflow.keras.losses import CategoricalCrossentropy
from tensorflow.keras import regularizers

In [ ]:
def model_creation():
    model = Sequential([
        Dense(10, activation = 'relu', kernel_regularizer = regularizers.l1(0.01), input_shape = (4,)),
        Dense(3, activation = 'softmax')
        ])

    model.compile(
            optimizer = SGD(learning_rate = 0.1),
            loss = CategoricalCrossentropy(),
            metrics = ['accuracy']
        )
    return model

In [ ]:
model1 = model_creation()
pred1 = model1.predict(x_test)
print(pred1)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
[[0.25510025 0.38034478 0.36455494]
 [0.17330354 0.4901253  0.3365712 ]
 [0.42276216 0.2913186  0.28591934]
 [0.26557148 0.36988214 0.36454654]
 [0.4325919  0.2807165  0.28669155]
 [0.2132721  0.42527443 0.36145335]
 [0.25130206 0.37345335 0.3752445 ]
 [0.39144152 0.29927102 0.3092874 ]
 [0.20583883 0.37355992 0.42060128]
 [0.24040003 0.37349424 0.38610578]
 [0.32072395 0.34917015 0.33010593]
 [0.18214723 0.46454486 0.35330787]
 [0.19924994 0.43481827 0.36593172]
 [0.18223602 0.4713164  0.34644762]
 [0.14384258 0.5734287  0.28272867]
 [0.31985876 0.35610202 0.32403925]
 [0.2371765  0.39530495 0.3675185 ]
 [0.16215293 0.41421437 0.42363265]
 [0.1817243  0.4188551  0.3994206 ]
 [0.22886702 0.38913888 0.38199416]
 [0.17069222 0.52064264 0.3086651 ]
 [0.24779618 0.3834673  0.36873654]
 [0.19453011 0.4906893  0.3147805 ]
 [0.23402219 0.3882511  0.37772664]
 [0.32275173 0.38476577 0.2924825 ]
 [0.32200152 0.33414337 0.3438551 ]
 [0.2431319  0.37838423 0.

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
#Model with Backpropagation
model2 = model_creation()
model2.fit(x_train, y_train, epochs = 100)
pred2 = model2.predict(x_test)
print(pred2)

Epoch 1/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3679 - loss: 1.2880  
Epoch 2/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5648 - loss: 1.0916 
Epoch 3/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8052 - loss: 0.9337
Epoch 4/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8435 - loss: 0.8332
Epoch 5/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8227 - loss: 0.7515
Epoch 6/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8385 - loss: 0.6686
Epoch 7/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8573 - loss: 0.6431 
Epoch 8/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8271 - loss: 0.6412
Epoch 9/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8358 - loss: 0.6136 
Epoch 10/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8554 - loss: 0.5519
Epoch 11/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8665 - loss: 0.5470
Epoch 12/100
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8842 - l

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step
[[8.77917465e-03 9.44690883e-01 4.65299897e-02]
 [9.77531672e-01 1.99388098e-02 2.52946420e-03]
 [6.79174832e-07 2.10587343e-04 9.99788761e-01]
 [9.07443557e-03 8.17955017e-01 1.72970474e-01]
 [4.46570665e-03 8.44433844e-01 1.51100382e-01]
 [9.56460714e-01 4.05341387e-02 3.00510833e-03]
 [3.12238298e-02 9.49043274e-01 1.97328683e-02]
 [1.43019992e-04 1.30731482e-02 9.86783862e-01]
 [1.49812608e-03 4.62599277e-01 5.35902619e-01]
 [1.51433256e-02 9.67875481e-01 1.69811547e-02]
 [1.36778329e-03 1.02349937e-01 8.96282256e-01]
 [9.83317673e-01 1.55540789e-02 1.12820149e-03]
 [9.79389787e-01 1.89431477e-02 1.66697067e-03]
 [9.84441161e-01 1.43780932e-02 1.18082413e-03]
 [9.93729651e-01 5.27039543e-03 9.99920652e-04]
 [1.23463785e-02 8.08434188e-01 1.79219380e-01]
 [5.02825460e-05 4.84582782e-03 9.95103836e-01]
 [1.47391865e-02 9.71816480e-01 1.34443864e-02]
 [1.37971584e-02 9.28357124e-01 5.78456447e-02]
 [3.44252949e-05 4.11757268e-03 9.95847940e-01]
 

In [ ]:
#Evaluate the Model -
loss, acc = model2.evaluate(x_test, y_test)
print("Loss:", loss, "\n")
print("Accuracy:", acc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 210ms/step - accuracy: 0.9667 - loss: 0.1763
Loss: 0.17632439732551575 

Accuracy: 0.9666666388511658


To avoid overfitting we have three methods -
1. Increase Dataset Size
2. Normalization
3. Dropouts

#Questions -
1. What is Deep Learning?
2. Tell about Deep Learning (feed forward layer)?
3. What is Neural Network?
4. What is Neurons?
5. What is Flatten layer, Dense layer?
6. What is activation function what is relu, tanh, softmax, sigmoid?
7. What is CNN. How we can import and use it?
8. What is filter?
9. What is RNN. How we can import and use it?
10. What is SimpleRNN and LSTM
11. What is Optimizer?
12. What is Backpropagation?
13. What is Regularization and it techniques (L1 & L2)?
14. What is Overfitting and Underfitting and how to avoid them?
15. what is Dropout (method of avoiding overfitting)?
16. Why we need Backpropagation and Optimizer?
17. What is Pixel(28/28, 1D, 784)?