<a href="https://colab.research.google.com/github/thekhush11/GenAI-Colab-Projects/blob/main/NLP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#NLP -
1. Tokenization
2. Embedding (Word2Vec, Glove)
3. Bag-of-Word and TF-IDP

NLP - Natural Language Processing is a branch of Artificial Intelligence that helps computer to understand, interprete, generate human languaga.

NLP Applications - Search Engine, Chatbots, Email Filtering, Speech to text, Grammer correction, Sentiment Analysis.

NLP Steps -

---
Tokenization -
Remove Stopwords
Stemming
Vectorization
Model Prediction

Basic Input -
"NLP is the best branch of AI"
"MLP""is""the""best""brance""of""AI"

In [ ]:
import nltk #nltk is the python librabry that is used for working in human language data
nltk.download('punkt')
nltk.download('punkt_tab') # Download the missing resource
from nltk.tokenize import word_tokenize
data = "I’m thrilled to share that I’ve earned the 50 Days Badge 2025 on LeetCode! This represents 50+ days of consistent problem-solving, learning, and growing in the world of data structures and algorithms."
Processed_Data = word_tokenize(data)
for i in Processed_Data:
  print(i)
print(len(Processed_Data))

I
’
m
thrilled
to
share
that
I
’
ve
earned
the
50
Days
Badge
2025
on
LeetCode
!
This
represents
50+
days
of
consistent
problem-solving
,
learning
,
and
growing
in
the
world
of
data
structures
and
algorithms
.
40


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


In [ ]:
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
Data1 = set(stopwords.words('english'))
data2 = []
for i in Processed_Data:
  if i.lower() not in Data1:
    data2.append(Processed_Data)
print(len(data2))

25


[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


#Stemming -
Reduce word to there base root or form

In [ ]:
from nltk.stem import PorterStemmer
Stemmer = PorterStemmer()
data3 = []
for i in Processed_Data:
  data3.append(Stemmer.stem(i))
print(data3)

['i', '’', 'm', 'thrill', 'to', 'share', 'that', 'i', '’', 've', 'earn', 'the', '50', 'day', 'badg', '2025', 'on', 'leetcod', '!', 'thi', 'repres', '50+', 'day', 'of', 'consist', 'problem-solv', ',', 'learn', ',', 'and', 'grow', 'in', 'the', 'world', 'of', 'data', 'structur', 'and', 'algorithm', '.']


#Vectorization -
It is a techniques that convert text into a numeric vector
#Type of Vectorization -
1. Bag of Words (BoW) - Bag of words count a word how many times appears in a whole documents
2. TF-IDF
3. Embedding

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
text = ["Natural Language Processing (NLP) is a branch of artificial intelligence (AI) that enables computers to understand, interpret, manipulate, and generate human language.", "It's an interdisciplinary field that combines computer science, AI, and linguistics to process large amounts of text and speech data."]

Vector = CountVectorizer()
New_text = Vector.fit_transform(text)
print(Vector.get_feature_names_out())
print(New_text.toarray())

['ai' 'amounts' 'an' 'and' 'artificial' 'branch' 'combines' 'computer'
 'computers' 'data' 'enables' 'field' 'generate' 'human' 'intelligence'
 'interdisciplinary' 'interpret' 'is' 'it' 'language' 'large'
 'linguistics' 'manipulate' 'natural' 'nlp' 'of' 'process' 'processing'
 'science' 'speech' 'text' 'that' 'to' 'understand']
[[1 0 0 1 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 2 0 0 1 1 1 1 0 1 0 0 0 1 1 1]
 [1 1 1 2 0 0 1 1 0 1 0 1 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 1 1 1 1 1 0]]


#IF - TDF

IF - How frequently they appear in the whole documnet

IDF - how rear they are in the whole document

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
vectors = tfidf.fit_transform(text)
print(tfidf.get_feature_names_out())
print(vectors.toarray())

['ai' 'amounts' 'an' 'and' 'artificial' 'branch' 'combines' 'computer'
 'computers' 'data' 'enables' 'field' 'generate' 'human' 'intelligence'
 'interdisciplinary' 'interpret' 'is' 'it' 'language' 'large'
 'linguistics' 'manipulate' 'natural' 'nlp' 'of' 'process' 'processing'
 'science' 'speech' 'text' 'that' 'to' 'understand']
[[0.15702636 0.         0.         0.15702636 0.22069507 0.22069507
  0.         0.         0.22069507 0.         0.22069507 0.
  0.22069507 0.22069507 0.22069507 0.         0.22069507 0.22069507
  0.         0.44139013 0.         0.         0.22069507 0.22069507
  0.22069507 0.15702636 0.         0.22069507 0.         0.
  0.         0.15702636 0.15702636 0.22069507]
 [0.16747189 0.23537589 0.23537589 0.33494377 0.         0.
  0.23537589 0.23537589 0.         0.23537589 0.         0.23537589
  0.         0.         0.         0.23537589 0.         0.
  0.23537589 0.         0.23537589 0.23537589 0.         0.
  0.         0.16747189 0.23537589 0.         0.235

#Embedding -
Word Embedding is mapped each word to a vector of real number
* Types of Embedding -
1. Word2Vec
2. Glove

In [ ]:
import gensim.downloader as api

#model1 = api.load("word2vec-google-news-300") (Very Big Data)
model1 = api.load("glove-wiki-gigaword-50")
print(model1)

KeyedVectors<vector_size=50, 400000 keys>


In [ ]:
vector = model1['computer']
print(vector[:10])

[ 0.079084 -0.81504   1.7901    0.91653   0.10797  -0.55628  -0.84427
 -1.4951    0.13418   0.63627 ]


In [ ]:
simi = model1.most_similar("computer", topn = 5)
for i in simi:
  print(i)

('computers', 0.9165045022964478)
('software', 0.8814992904663086)
('technology', 0.852556049823761)
('electronic', 0.812586784362793)
('internet', 0.8060455322265625)


In [ ]:
# Attention Mechanism
! pip install torch # installing pytorch

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 39.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 31.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 22.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 10.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 45.0 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

In [ ]:
import torch
import torch.nn as nn
import torch.functional as fn

In [ ]:
text = ['The','Man','Work']
print(text)

e_d = 8

w_idx = {i: index for index, i in enumerate(text)}
print(w_idx)

idx_w = torch.tensor([w_idx[i] for i in text])
print(idx_w)

['The', 'Man', 'Work']
{'The': 0, 'Man': 1, 'Work': 2}
tensor([0, 1, 2])


In [ ]:
embed = nn.Embedding(num_embeddings=len(w_idx), embedding_dim=e_d)

In [ ]:
embeded = embed(idx_w)
print(embeded)

tensor([[-0.5570,  0.1775,  0.0736,  0.2351, -0.0933,  0.7444,  2.0711, -0.7837],
        [ 0.3476, -0.6201, -1.1404, -0.4639, -0.4886, -0.5831, -1.8925,  0.7743],
        [-0.6554, -1.5103, -0.2854,  0.0617,  1.1055, -1.4175,  1.0914,  1.1751]],
       grad_fn=<EmbeddingBackward0>)


In [ ]:
embeded = embeded.unsqueeze(0)
embeded

tensor([[[-0.5570,  0.1775,  0.0736,  0.2351, -0.0933,  0.7444,  2.0711,
          -0.7837],
         [ 0.3476, -0.6201, -1.1404, -0.4639, -0.4886, -0.5831, -1.8925,
           0.7743],
         [-0.6554, -1.5103, -0.2854,  0.0617,  1.1055, -1.4175,  1.0914,
           1.1751]]], grad_fn=<UnsqueezeBackward0>)

In [ ]:
num_head = 2
multi_head = nn.MultiheadAttention(embed_dim=e_d, num_heads=num_head, batch_first=True)

In [ ]:
multi_head

MultiheadAttention(
  (out_proj): NonDynamicallyQuantizableLinear(in_features=8, out_features=8, bias=True)
)

In [ ]:
a_output, a_weights = multi_head(embeded, embeded, embeded)

In [ ]:
a_output

tensor([[[ 0.3530, -0.1305,  0.0624, -0.0749,  0.0374,  0.1219,  0.0560,
          -0.0416],
         [ 0.2830, -0.1359,  0.0139, -0.0946,  0.0360,  0.0853,  0.0891,
          -0.0794],
         [ 0.2437, -0.1475,  0.0226, -0.0900,  0.0749,  0.0792,  0.0481,
          -0.0613]]], grad_fn=<TransposeBackward0>)

In [ ]:
a_weights

tensor([[[0.2682, 0.3547, 0.3771],
         [0.2870, 0.3420, 0.3710],
         [0.2780, 0.2874, 0.4346]]], grad_fn=<MeanBackward1>)

In [ ]:
Attention_weights = a_weights.squeeze(0).detach().numpy()
print(Attention_weights)

[[0.26816154 0.35473323 0.37710524]
 [0.28703555 0.3419661  0.37099838]
 [0.27799302 0.2874279  0.43457907]]


In [ ]:
a_output.squeeze(0).detach().numpy()

array([[ 0.35296366, -0.13052626,  0.0623667 , -0.07486105,  0.03735699,
         0.12187997,  0.05600118, -0.04160852],
       [ 0.28301817, -0.13591531,  0.01385718, -0.09463891,  0.0360448 ,
         0.08533718,  0.08911539, -0.07939664],
       [ 0.24372803, -0.14749539,  0.02260449, -0.09001815,  0.07485964,
         0.07919444,  0.04807313, -0.06129366]], dtype=float32)

In [ ]:
import torch
from transformers import MarianMTModel, MarianTokenizer
model = 'Helsinki-NLP/opus-mt-en-hi'
tok = MarianTokenizer.from_pretrained(model)
models = MarianMTModel.from_pretrained(model)

In [ ]:
input_text = ['Hitanshi is mad']

tok_input = tok(input_text,return_tensors='pt', padding = True, truncation = True)

In [ ]:
translate = models.generate(**tok_input)

In [ ]:
output = tok.batch_decode(translate, skip_special_tokens=True)
print(output)

['हिटशी पागल है']


#Topics -
Read them thoroughly
* NumPy
* Pytorch
* Keras
* TensorFlow
* SeaBorn
* MatPlotLib
* NLTK
* Transformer (Hugging Face Library)
* Gensim
* Langdetect
* OpenCV
* PILLOW (pil)
* TorchVision
* FastAI

# Make CNN mask detection using CNN and Open CV