<a href="https://colab.research.google.com/github/thekhush11/GenAI-Colab-Projects/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

03/07/2025

In [ ]:
mylist = [1, 2, 3]
print(mylist)
print(type(mylist))

[1, 2, 3]
<class 'list'>


In [ ]:
import numpy as np
myNpList = np.array(mylist)
print(myNpList)
print(type(myNpList))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
sample_list_of_list = ([[1,2,3],[4,5,6],[7,8,9]])
type(sample_list_of_list)

list

In [ ]:
sample_matrix = np.array(sample_list_of_list)
sample_list_of_list

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [ ]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
a.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [ ]:
c = np.random.rand(4)
type(c)

numpy.ndarray

In [ ]:
np.random.rand(3,4,5)

array([[[0.13381342, 0.58346195, 0.12573099, 0.76773653, 0.59420706],
        [0.61720211, 0.39433413, 0.57538314, 0.01696323, 0.59687146],
        [0.49222822, 0.50824011, 0.54241397, 0.04581505, 0.44333118],
        [0.12776222, 0.84429043, 0.77730312, 0.79660943, 0.58240291]],

       [[0.87603226, 0.3817519 , 0.02701328, 0.15113748, 0.83905701],
        [0.33772722, 0.38630614, 0.05523366, 0.31106816, 0.02163736],
        [0.26077015, 0.46161267, 0.92730178, 0.79755845, 0.14487601],
        [0.7804876 , 0.13212649, 0.96353844, 0.0622815 , 0.2959941 ]],

       [[0.3398992 , 0.55092046, 0.03120535, 0.67150106, 0.87004978],
        [0.40534388, 0.46796289, 0.15441191, 0.80179575, 0.35779503],
        [0.31069268, 0.0460861 , 0.55667   , 0.12368701, 0.24834062],
        [0.16484599, 0.63229807, 0.52452552, 0.57068629, 0.36595047]]])

In [ ]:
#This random.rand function generate uniformly distributed number from 0 to 1

Normal Distribution center arount 0

In [ ]:
b = np.random.randn(3,4)
b

array([[-0.87207258,  1.07778424, -0.52520092,  2.54215564],
       [-0.17845897, -2.1872946 , -0.14402735,  0.20171941],
       [ 1.31192357,  0.79930421, -0.7019324 , -1.18720954]])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
b.shape

(3, 4)

In [ ]:
b.dtype

dtype('float64')

In [ ]:
random_arr = np.random.randint(10, 50, 5)
random_arr

array([18, 25, 23, 12, 30])

In [ ]:
random_arr.max()

np.int64(30)

In [ ]:
random_arr.shape

(5,)

In [ ]:
random_arr.argmin()

np.int64(3)

04/07/2025

Array and Matrix Index

In [ ]:
import numpy as np
sample_arr = np.arange(1,11)
sample_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sample_arr[2]

np.int64(3)

In [ ]:
sample_arr[0:4]

array([1, 2, 3, 4])

In [ ]:
sample_mat = np.array([[1,2,3],[4,5,6],[6,7,8]])
sample_mat

array([[1, 2, 3],
       [4, 5, 6],
       [6, 7, 8]])

In [ ]:
sample_mat[0]

array([1, 2, 3])

In [ ]:
sample_mat[1,1]

np.int64(5)

In [ ]:
sample_mat[1][1]

np.int64(5)

In [ ]:
sample_mat[1:3,1:3]

array([[5, 6],
       [7, 8]])

In [ ]:
print(sample_mat[:2,1:])
print(sample_mat[1,1:])
print(sample_mat[0:5])

[[2 3]
 [5 6]]
[5 6]
[[1 2 3]
 [4 5 6]
 [6 7 8]]


Broadcasting, Slice, Copy

In [ ]:
sample_arr[0:3] = 400
sample_arr

array([400, 400, 400,   4,   5,   6,   7,   8,   9,  10])

In [ ]:
print(id(sample_arr[0:5]))
slice_of_sample_arr = sample_arr[0:5]
s = slice_of_sample_arr
print(id(slice_of_sample_arr))
print(id(sample_arr))
print(id(s))

137114642303760
137114642303760
137114642949552
137114642303760


In [ ]:
slice_of_sample_arr[:] = 100
print(slice_of_sample_arr)
print(sample_arr)

[100 100 100 100 100]
[100 100 100 100 100   6   7   8   9  10]


In [ ]:
sample_arr_copy = sample_arr.copy()
sample_arr_copy

array([100, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [ ]:
sample_arr_copy[0:5] = 500
print(sample_arr_copy)
print(sample_arr)
print(id(sample_arr_copy))
print(id(sample_arr))

[500 500 500 500 500   6   7   8   9  10]
[100 100 100 100 100   6   7   8   9  10]
137114641710800
137114642949552


Checking Conditions

In [ ]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Difference between arange and range funtion

In [ ]:
boolean_arr = arr > 5
print(boolean_arr)
print(type(boolean_arr))

[False False False False False  True  True  True  True  True]
<class 'numpy.ndarray'>


In [ ]:
arr[boolean_arr]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[arr <= 5]

array([1, 2, 3, 4, 5])

In [ ]:
a = np.arange(0,11)
print(a)
b = np.dot(a,100)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10]
[   0  100  200  300  400  500  600  700  800  900 1000]


In [ ]:
#3D Vectors
a = np.array([1,2,3])
b = np.array([4,5,6])
cross_product_3d = np.cross(a,b)
print(cross_product_3d)

[-3  6 -3]


In [ ]:
#2D Vector
x = np.array([1,2])
y = np.array([3,4])
cross_product = np.cross(x,y)
print(cross_product)

-2


Q. Implement a Bubble sort in the Python

In [ ]:
print(a/a)

[1. 1. 1.]


In [ ]:
print(1/a)

[1.         0.5        0.33333333]


In [ ]:
import numpy
coefficient = [12,3,4,5,10]
polynomialExp = numpy.poly1d(coefficient)
print("type of polynomial = ", type(polynomialExp))
print("Polynomial expression is: ", polynomialExp)
print(polynomialExp)
x = 2
result = polynomialExp(x)
print(result)

type of polynomial =  <class 'numpy.poly1d'>
Polynomial expression is:      4     3     2
12 x + 3 x + 4 x + 5 x + 10
    4     3     2
12 x + 3 x + 4 x + 5 x + 10
252


In [ ]:
import numpy
a = numpy.matrix(((10,20,30), (50,60,70), (11,22,33)))
print("a : \n", a)
b = numpy.transpose(a)
print("Transpose of a : \n", b)

a : 
 [[10 20 30]
 [50 60 70]
 [11 22 33]]
Transpose of a : 
 [[10 50 11]
 [20 60 22]
 [30 70 33]]


In [ ]:
import numpy as np

# 2x2 matrix
matrix = np.array([[1, 2], [3, 4]])

determinant = np.linalg.det(matrix)

print("Determinant of 2x2 matrix:", determinant)

# 3x3 matrix
matrix_3x3 = np.array([[2, 4, 6], [0, -2, 1], [5, 0, 3]])

determinant_3x3 = np.linalg.det(matrix_3x3)

print("Determinant of 3x3 matrix:", determinant_3x3)


Determinant of 2x2 matrix: -2.0000000000000004
Determinant of 3x3 matrix: 67.99999999999996


In [ ]:
#Identity Matrix
a = numpy.identity(10)
print(type(a))
print(f"10x10 Identity Matrix:{a}")

<class 'numpy.ndarray'>
10x10 Identity Matrix:[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
a = numpy.matrix(((10,20,30,40),(50,60,70,80),(90,100,110,120),(2,3,4,5)))
b = numpy.hsplit(a,2)
print('a : \n',a)
print('b : \n',b)
c = b[0]
print('c : \n',c)
d = b[1]
print('d : \n',d)
e = numpy.vsplit(c,2)
print('e : \n',e)
f = numpy.vsplit(d,2)
print('f : \n',f)

a : 
 [[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]
 [  2   3   4   5]]
b : 
 [matrix([[ 10,  20],
        [ 50,  60],
        [ 90, 100],
        [  2,   3]]), matrix([[ 30,  40],
        [ 70,  80],
        [110, 120],
        [  4,   5]])]
c : 
 [[ 10  20]
 [ 50  60]
 [ 90 100]
 [  2   3]]
d : 
 [[ 30  40]
 [ 70  80]
 [110 120]
 [  4   5]]
e : 
 [matrix([[10, 20],
        [50, 60]]), matrix([[ 90, 100],
        [  2,   3]])]
f : 
 [matrix([[30, 40],
        [70, 80]]), matrix([[110, 120],
        [  4,   5]])]
